FROM node:16.16.0-alpine3.16

# set working directory
WORKDIR /app
# install and cache app dependencies
COPY ./frontend/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@14.2.0

# add app
COPY ./frontend /app

# start app
CMD ng serve --host 0.0.0.0
