FROM node:16.16.0-alpine3.16

# set working directory
WORKDIR /app
# install and cache app dependencies
COPY ../backend/package.json /app/package.json
RUN npm install

# add app
COPY ./backend /app

# start app
CMD npm run dev