FROM node:16.16.0-alpine3.16 as build-step

# set working directory

RUN mkdir -p /app
WORKDIR /app
# install and cache app dependencies
COPY ./frontend/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@14.2.0

# add app
COPY ./frontend /app

RUN npm run build --prod

FROM nginx:1.17.1-alpine

COPY --from=build-step /app/dist/frontend /usr/share/nginx/html